### ISSUE TITLE
El usuario no está obligado a responder todas las preguntas para conocer a la Media Naranja.

### ISSUE THREAD

**Issue by RCGTDev** [ciudadanointeligente/votainteligente-portal-electoral#226]

**Comment by martinszy** [comment]
En el caso de Argentina tampoco vamos a requerir todas las respuestas, se pueden saltear preguntas.

**Comment by RCGTDev** [comment]
En este momento la prioridad está en que funcione la media naranja, aunque se tengan que responder todas las preguntas.
