### ISSUE TITLE
Admin: Filtrar taken positions

### ISSUE THREAD

**Issue by martinszy** [ciudadanointeligente/votainteligente-portal-electoral#242]
Al seleccionar una "taken position", me saltan tooodas las opciones y es un chino buscar la respuesta para lo que busco. Estaría bueno que me permita filtrar para ir seleccionando por partes: elección, topic (pregunta) y ahi me filtre las 4 opciones de rta posibles

**Comment by lfalvarez** [comment]
Para Agustina
