### ISSUE TITLE
Admin: Mostrar election en los listados de topics y quesiton categories

### ISSUE THREAD

**Issue by martinszy** [ciudadanointeligente/votainteligente-portal-electoral#245]
Que me aparezcan dos columnas o algo así para identificar a qué elección me refiero cuando hablo de un topic o una question category

**Comment by lfalvarez** [comment]
Entonces tenemos:
* [ ] Topic
* [ ] QuestionCategory

**Comment by lfalvarez** [comment]
@martinszy faltan otros podrías ayudarme? y listarlo acá?

**Comment by martinszy** [comment]
Estamos poniendo el nombre de la elección en el nombre de la pregunta para poder encontrarla, esto no puede quedar en el front-end del sitio, hay que arreglar este tema de la búsqueda o hacer un hack en el front-end para ocultar el nombre de la provincia.

**Comment by martinszy** [comment]
Ok, solucionado.
