### ISSUE TITLE
Answer value es 0

### ISSUE THREAD

**Issue by martinszy** [ciudadanointeligente/votainteligente-portal-electoral#253]
¿Cómo hará el código del juego para diferenciar entre las 4 respuestas posible si el anwer value es 0 en todas?

http://elecciones2015.yoquierosaber.org/theme/election/pre-candidato-a-presidente/media-naranja.json

{
category_id: 10,
name: "Vivienda",
questions: [
{
question_text: "¿Creés que ante una ocupación ilegal de terrenos lo mejor es la radicación de una villa?",
answers: [
{
answer_value: 0,
answer_text: "Sí, siempre y cuando los terrenos sean habitables",
answer_id: 165
},
{
answer_value: 0,
answer_text: "Sí, siempre y cuando no se ocupen terrenos privados",
answer_id: 166
},
{
answer_value: 0,
answer_text: "No, pero se debe dar una vivienda digna en terrenos habilitados",
answer_id: 167
},
{
answer_value: 0,
answer_text: "No, es una usurpación ilegal de terrenos del Estado",
answer_id: 168
}
],

**Comment by lfalvarez** [comment]
@martinszy una pregunta y esto no se soluciona con utilizar el answer_id?

**Comment by martinszy** [comment]
Habría que asumir que el menor answer_id es la respuesta más positiva, y el
mayor answer_id es la respuesta más negativa.
Podemos hacer eso, pero entonces no tiene sentido el answer_value y habría
que eliminarlo.
De todas maneras me parece que si llegamos a eliminar y volver a crear una
respuesta, el answer_id podría quedar con un valor diferente, y por eso se
hace necesario el answer_value, no te parece?

Quizás habría que agregar en el admin de cada respuesta el tipo de
respuesta: SuperSI - SIpero -  NOpero - SuperNO

Funcionará eso?



El 8 de julio de 2015, 15:31, Luis Felipe Álvarez Burgos <
notifications@github.com> escribió:

> @martinszy <https://github.com/martinszy> una pregunta y esto no se
> soluciona con utilizar el answer_id?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ciudadanointeligente/votainteligente-portal-electoral/issues/253#issuecomment-119690347>
> .
>



-- 
*Martín Szyszlican*
Desarrollo web usable y accesible
martinszyszlican.com

**Comment by lfalvarez** [comment]
Esa es un poco mi pregunta, puedo agregar un answer_value y una relación entre positivo (+2) negativo (-2), pero creo que eso lo tienen que agregar a mano o no? y si se puede hacer que el administrador elija así como dices y sería algo de este estilo:
```
ANSWER_VALUES = (
    (-2, 'Muy negativo'),
    (-1, 'Negativo'),
    (0, 'Neutro'),
    (1, 'Positivo'),
    (2, 'Muy Positivo'),
)
```
Sin embargo, serían ustedes los encargados de seleccionar cual es la respuesta más positiva yla más negativa. Te parece buena opción?

**Comment by martinszy** [comment]
Si, me parece bien.
Pero además me parece que se puede pre-llenar el valor de esa respuesta en base, como tu dices más arriba, al answer_id, porque creo que en este momento si se respeta eso de que el menor id es el muy positivo.

menor answer_id = answer_value 2
+1 = answer_value 1
+2 = answer+value -1
mayor answer_id = anser_value -2

Y cuando se crea una nueva, se puede poner en cero... o en null.

**Comment by lfalvarez** [comment]
Podría llenarlo automáticamente ahora pero creo que para el futuro no me agradaría tener que suponer que la persona empezará a rellenar pensando en el más positivo o negativo.

**Comment by martinszy** [comment]
Estamos de acuerdo, que sea automático por única vez, para no tener que
volver a cargar las que ya están.

Abrazo!

El 8 de julio de 2015, 15:52, Luis Felipe Álvarez Burgos <
notifications@github.com> escribió:

> Podría llenarlo automáticamente ahora pero creo que para el futuro no me
> agradaría tener que suponer que la persona empezará a rellenar pensando en
> el más positivo o negativo.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ciudadanointeligente/votainteligente-portal-electoral/issues/253#issuecomment-119695548>
> .
>



-- 
*Martín Szyszlican*
Desarrollo web usable y accesible
martinszyszlican.com

**Comment by lfalvarez** [comment]
Qué te parece cómo quedó el JSON? para lo del admin te podrías esperar un poco?

**Comment by jpamato** [comment]
Buenas, necesitaría para establecer los puntajes que las opciones de respuesta vayan de 
0 (Si), 1 (Si, pero...), 2 (No, pero), 3 (No), 
¿puede ser?

**Comment by lfalvarez** [comment]
Lo cambio? es creo sólo cambiar la escala.

**Comment by jpamato** [comment]
eso podría estar en "answer value", o sacar ese valor de la operacion answer_id%4

**Comment by lfalvarez** [comment]
Te lo puedo cambiar no te preocupes :smile:

**Comment by jpamato** [comment]
gracias :)

**Comment by martinszy** [comment]
El json lo veo igual ahora, los valores no me preocupan, sólo que se pueda
diferenciar.

Abrazo!

2015-07-08 16:59 GMT-03:00 Luis Felipe Álvarez Burgos <
notifications@github.com>:

> Te lo puedo cambiar no te preocupes [image: :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ciudadanointeligente/votainteligente-portal-electoral/issues/253#issuecomment-119714951>
> .
>



-- 
*Martín Szyszlican*
Desarrollo web usable y accesible
martinszyszlican.com

**Comment by lfalvarez** [comment]
Qué tal ahora?

**Comment by martinszy** [comment]
Perfect!

2015-07-08 17:03 GMT-03:00 Luis Felipe Álvarez Burgos <
notifications@github.com>:

> Qué tal ahora?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ciudadanointeligente/votainteligente-portal-electoral/issues/253#issuecomment-119715801>
> .
>



-- 
*Martín Szyszlican*
Desarrollo web usable y accesible
martinszyszlican.com

**Comment by martinszy** [comment]
Esto está funcionando bien.
