### ISSUE TITLE
Arreglar footer, qué debe decir?

### ISSUE THREAD

**Issue by lfalvarez** [ciudadanointeligente/votainteligente-portal-electoral#255]
Debe decir las cosas relevantes a Red Ciudadana y cómo contactarlos.

**Comment by RCGTDev** [comment]
- En el centro logos de Global Shapers (https://www.globalshapers.org/hubs/guatemala-city) , Red Ciudadana (http://www.redciudadana.org/)  y Ciudadano Inteligente.

- En la derecha el contacto: 
Correo: info@redciudadana.org.gt
Dirección: 12 calle 1-25 zona 10 Edificio Géminis 10 Torre Norte Oficina 1413 

- En la izquierda: 

Ayúdanos a llegar a más personas. 
Donaciones (https://www.indiegogo.com/projects/help-guatemala-vote--2#/story) 
Voluntariado (http://voluntarios.redciudadana.org/)

**Comment by lfalvarez** [comment]
:+1:
