### ISSUE TITLE
Cambiar los textos para compartir en Facebook y Twitter

### ISSUE THREAD

**Issue by lfalvarez** [ciudadanointeligente/votainteligente-portal-electoral#256]
Debe tener un hashtag como por ejemplo #candidatosgt ?

**Comment by RCGTDev** [comment]
Si Felipe, la interacción en redes es de prioridad alta también y el hashtag que estaremos usando es #CandiDATOSgt

**Comment by lfalvarez** [comment]
Estamos listos ocn esto parece
