### ISSUE TITLE
Agregar en el footer los cuadros con links de la maqueta. 

### ISSUE THREAD

**Issue by RCGTDev** [ciudadanointeligente/votainteligente-portal-electoral#264]

**Comment by lfalvarez** [comment]
Podrían colocar la maqueta acá? creo que no la tengo a mano.

**Comment by RCGTDev** [comment]
Felipe, necesitas que nosotros hagamos el diseño de los cuadros del footer? O solo te indicamos el texto y el linnk al que redirige? 


![uploads/3749b538-b85e-48ec-a6e1-763a7d564aff/MaquetaVI.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F3749b538-b85e-48ec-a6e1-763a7d564aff%2FMaquetaVI.png)

**Comment by lfalvarez** [comment]
Sería maravilloso si ustedes pueden diseñar los logos en el footer y luego me envían los links a los que debe apuntar

**Comment by RCGTDev** [comment]
Felipe, aquí te adjunto los logos para el footer y el link. Hay distintos logos para cada sección de la plataforma por lo que te comparto el cuadro y los logos, con el link, que deben ir en cada página: 

1. Home 

- Dónde Voto http://elecciones2015.tse.org.gt/CentrosdeVotacion-16.html#
- Compáralos (Frente a frente) http://guatemala.votainteligente.org/election/presidencial/face-to-face
- Propuestas (Cuestionario) http://guatemala.votainteligente.org/election/presidencial/questionary

2. Página dónde se hace la 1/2 Naranja 

- Perfiles: http://guatemala.votainteligente.org/election/presidencial
- Propuestas: http://guatemala.votainteligente.org/election/presidencial/questionary
- Compáralos: http://guatemala.votainteligente.org/election/presidencial/face-to-face

3. Página de Perfiles 

- Propuestas: http://guatemala.votainteligente.org/election/presidencial/questionary
- Compáralos: http://guatemala.votainteligente.org/election/presidencial/face-to-face
- Complemento Político: http://guatemala.votainteligente.org/election/presidencial/soul-mate

4. Página de Compáralos (Cambiamos el nombre de la funcionalidad Frente a Frente) 

- Propuestas: http://guatemala.votainteligente.org/election/presidencial/questionary
- Conócelos: http://guatemala.votainteligente.org/election/presidencial
- Ranking

5. Página de Propuestas (Cambiamos el nombre de la funcionalidad Cuestionario) 

- Conócelos: http://guatemala.votainteligente.org/election/presidencial
- Compáralos: http://guatemala.votainteligente.org/election/presidencial/face-to-face
- Ranking

6. Página de Pregúntales (Cuando esté lista) 

- Propuestas: http://guatemala.votainteligente.org/election/presidencial/questionary
- Conócelos: http://guatemala.votainteligente.org/election/presidencial
- Ranking

7. Página de Ranking 

- Propuestas: http://guatemala.votainteligente.org/election/presidencial/questionary
- Compáralos: http://guatemala.votainteligente.org/election/presidencial/face-to-face
- Conócelos: http://guatemala.votainteligente.org/election/presidencial

Adjunto las imágenes: 



![uploads/53e255b8-c63c-455e-8c34-c4e78f330a82/iconos.boton pagina web-01.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F53e255b8-c63c-455e-8c34-c4e78f330a82%2Ficonos.boton+pagina+web-01.jpg)

![uploads/ab5967f8-2b82-4b7c-b027-51ced34caa31/iconos.boton pagina web-05.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fab5967f8-2b82-4b7c-b027-51ced34caa31%2Ficonos.boton+pagina+web-05.jpg)

![uploads/6a7f8c38-d456-4c9e-8c00-33687095e9a0/iconos.boton pagina web-02.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F6a7f8c38-d456-4c9e-8c00-33687095e9a0%2Ficonos.boton+pagina+web-02.jpg)

![uploads/6e959d47-00bf-4e17-a57b-5f0535974e67/iconos.boton pagina web-04.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F6e959d47-00bf-4e17-a57b-5f0535974e67%2Ficonos.boton+pagina+web-04.jpg)

![uploads/16a271b1-2610-4e03-911e-539c123340c0/iconos.boton pagina web-07.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F16a271b1-2610-4e03-911e-539c123340c0%2Ficonos.boton+pagina+web-07.jpg)

![uploads/1b8d7f21-1e5a-404a-9fb8-4f52e40f4d23/iconos.boton pagina web-06.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F1b8d7f21-1e5a-404a-9fb8-4f52e40f4d23%2Ficonos.boton+pagina+web-06.jpg)

**Comment by RCGTDev** [comment]
![uploads/0bb85543-86bd-4256-9af7-93be79e4ae2a/iconos.boton pagina web-03.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F0bb85543-86bd-4256-9af7-93be79e4ae2a%2Ficonos.boton+pagina+web-03.jpg)
