### ISSUE TITLE
Cambios de diseño en página de candidato

### ISSUE THREAD

**Issue by martinszy** [ciudadanointeligente/votainteligente-portal-electoral#271]
Ej: http://elecciones2015.yoquierosaber.org/election/pre-candidato-a-presidente/jose-manuel-de-la-sota

1) La bio que aparezca al lado de la foto
2) Que cada respuesta incluya su texto completo
3) La foto con border-radius

**Comment by martinszy** [comment]
4)  En el texto de bio, aparece un "..." para seguir leyendo, Pondría un "leer más" en azulcito o algo así, para que se entienda. Si no se ve la flecha del medio, se entiende que el texto termina ahi

**Comment by martinszy** [comment]
Agregar el partido y sub partido si estan cargados (ya están todos los de presidente)

**Comment by lfalvarez** [comment]
Esto es muy del theme o no?

**Comment by martinszy** [comment]
Si lo es

**Comment by martinszy** [comment]
Copiado al repo del theme.
