### ISSUE TITLE
Candidate has_answered siempre en false

### ISSUE THREAD

**Issue by martinszy** [ciudadanointeligente/votainteligente-portal-electoral#272]
¿Cómo se hace para que deje de mostrar el enlace a twitter para candidatos que tienen todas las respuestas?
¿Cómo se hace para cambiar "pídele" por "pedile"?

**Comment by martinszy** [comment]
Además, en los casos en que las respuestas ya están, podría decir "leer sus propuestas" o algo así, hoy un usuario se confundió creyendo que el sitio era para pedirle las posicones a los candidatos en vez de para leerlas.

**Comment by martinszy** [comment]
"compáralo" con otro candidato. poner COMPARALO

**Comment by lfalvarez** [comment]
Sabes tengo un poco la duda, por que antes teníamos un flag por cada candidato, te parece si colocamos este dato en el candidate.extra_info? Aún estoy pensando en cómo debe ser que un candidato está marcado como has_answered o no.

**Comment by lfalvarez** [comment]
Quizás deba ser algo así como: Si al menos tiene una pregunta respondida entonces el has_answered = True. Qué piensan?

**Comment by lfalvarez** [comment]
Quizás deba ser algo así como: Si al menos tiene una pregunta respondida entonces el has_answered = True. Qué piensan?

**Comment by martinszy** [comment]
Si le falta alguna va en false, para que aparezca el link para pedirle su
posición

**Comment by lfalvarez** [comment]
Ya esa es mi pregunta, tenemos 2 opciones:
* Si tiene una respondida entonces el ```has_answer = True```
* Sólo si tienen todas respondidas  ```has_answer = True```
