### ISSUE TITLE
"Da la cara" no funciona

### ISSUE THREAD

**Issue by martinszy** [ciudadanointeligente/votainteligente-portal-electoral#273]
Al hacer el proceso de da la cara la etapa final de compartir en facebook no funciona.
aparece "undefined" en el campo de texto
y el elemento compartido en facebook es sólo la URL, no aparece el preview ni la foto que el usuairo se sacó

si no se puede arreglar fácil, deshabilitarlo

**Comment by lfalvarez** [comment]
si creo que podríamos deshabilitarlo por ahora por que quiero ver las implicancias de esta funcionalidad.

**Comment by martinszy** [comment]
ok, lo oculto en el template o tiene una opcion de configuración?

veamos de habiltarlo la semana que viene, si?

El 27 de julio de 2015, 22:15, Luis Felipe Álvarez Burgos <
notifications@github.com> escribió:

> si creo que podríamos deshabilitarlo por ahora por que quiero ver las
> implicancias de esta funcionalidad.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ciudadanointeligente/votainteligente-portal-electoral/issues/273#issuecomment-125399500>
> .
>



-- 
*Martín Szyszlican*
Desarrollo web usable y accesible
martinszyszlican.com

**Comment by martinszy** [comment]
Ok, deshabilitado por ahora, creo otro issue para habilitarlo.
