### ISSUE TITLE
Cambiar el Favicon y el texto de la pestaña. 

### ISSUE THREAD

**Issue by RCGTDev** [ciudadanointeligente/votainteligente-portal-electoral#280]

**Comment by lfalvarez** [comment]
Existe el favicon? es el título de la página?

**Comment by RCGTDev** [comment]
El Titulo CandiDatos - Red Ciudadana & Global Shapers,

El favicon seria el isotipo geolocalizacion de CandiDatos

**Comment by RCGTDev** [comment]
Adjunto la imagen para el favicon


![uploads/6c2c4ce9-2167-4a0d-bf60-57fb203c27a7/icono candiDATOS-01-01.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F6c2c4ce9-2167-4a0d-bf60-57fb203c27a7%2Ficono+candiDATOS-01-01.png)
