### ISSUE TITLE
Logos de los partidos políticos. 

### ISSUE THREAD

**Issue by RCGTDev** [ciudadanointeligente/votainteligente-portal-electoral#281]
Actualmente solo sale el link. Se puede poner la imagen del partido ubicada encima de dónde van las redes sociales en el perfil?

**Comment by lfalvarez** [comment]
Podrían contarme un poco más cómo se lo imaginan?

**Comment by RCGTDev** [comment]
La idea es que no este solo el link de partido politico, sino que se encuentre la imagen o logo del Partido Político, El logo debe encontrarse arriba de las redes sociales del candidato.  Link de Referencia https://gm1.ggpht.com/ju8lXL9pvHI07JPzuqQaySoZ5t0ekvbt_smFoqUxQc_XGkzqBcZbG5wFAnWKAfqCJn4vLLG95A9zVXhNMu64yxSR0LGMn3-yvzmv4BZQfjP36NdJlhPqpCCFV-4NICiSAfnxA9FCkLFQsAJ8sDXdqGicOjINJaER-9xSezxs60Nh-K9FZ1Bg7_GBmOjN8lyQNiajFk3B_3elTxRyJF5HerBEZX7kUP4DcFBp4-_uIuEQy3KBbdgUqsZvMEi7MqHNEHg6KuAM7auSDbMTO0I_T1cudytWh8WDXqGrP_xEgM1LaylwEyKsCy7wsgJ7_cibFKbhvUcRsFGz14jkIAex5XyskPSOBdZhfYcGBomCWkknikl1oPxdpenvpjKZqfuXqW3oiJAiYDNWh8ujpZDCtc-KkLX9EjfORAqi8fA_x5xBdSDs3rMK3ZLSOx7qbxATFW8XuX4F92xwQ1TnA4smM03RPJN6JHh09f9IT3GHYP8kYlePpm6xSL-il-YCIFVka2EY3qalqmfmx_4xnNf8IHJNnJWITLS7WuYYulvxhJZ2ScObcB68YsntFKwDqy8e_YPTHfgWdKD6dCAKuOZNcaA4MHXVD9vAcrX1c_Y3Hb1jFLdY0ycDjg=w1342-h539-l75-ft

**Comment by lfalvarez** [comment]
Perdón no pude acceder, me tira un error 403, me lo imaginé así ![Imgur](http://i.imgur.com/4aF2B1Q.png)
