### ISSUE TITLE
Cuestionario: agregar información adicional para dejar clara la pregunta. 

### ISSUE THREAD

**Issue by RCGTDev** [ciudadanointeligente/votainteligente-portal-electoral#291]

**Comment by RCGTDev** [comment]
![uploads/a0415e3b-49f4-4da9-a6a6-acd7bef6a492/Más información.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fa0415e3b-49f4-4da9-a6a6-acd7bef6a492%2FM%C3%A1s+informaci%C3%B3n.png)


un botón que diga más información y que nos permita poner la explicación en texto, de varios conceptos que hay en las respuestas.

**Comment by lfalvarez** [comment]
Chicos tienen que agregarle una descripción a cada pregunta

**Comment by lfalvarez** [comment]
![screenshot from 2015-08-04 18 42 30](https://cloud.githubusercontent.com/assets/585757/9073582/c06c8742-3ad8-11e5-8d10-09b4b2403a11.png)
