### ISSUE TITLE
Mejorar ejemplos del Formularioi de recolección de propuestas ciudadanas

### ISSUE THREAD

**Issue by lfalvarez** [ciudadanointeligente/votainteligente-portal-electoral#329]
Tienen mejores jemplos o textos de ayuda???

* [ ] Según la óptica de tu organización, describe un problema de tu comuna que quieras solucionar. líneas) -> Ej: Poca participación en el Plan Regulador, falta de transparencia en el trabajo de la municipalidad, pocos puntos de reciclaje, etc.'))
* [x] Qué quieres que haga tu autoridad para solucionar el problema? (3 líneas) -> Ejemplo: "Que se aumenten en 30% las horas de atención de la especialidad Cardiología en los Cesfam y consultorios de la comuna", "Que se publiquen todos los concejos municipales en el sitio web del municipio".
* [x] "¿Qué avances concretos esperas que se logren durante el periodo del alcalde (4 años)?" -> Acá falta un ejemplo
* [ ] ¿En qué plazo te gustaría que esté solucionado?' -> quizás acá nos falta una ayuda.
* [ ] Título corto -> "Un título que nos permita describir tu propuestaciudadana. Ej: 50% más de ciclovías para la comuna"
* [ ] ¿Cómo clasificarías tu propuesta? -> quizás acá nos falta una ayuda.
* [ ] ¿Quiénes son tus posibles aliados? -> quizás acá nos falta una ayuda.

**Comment by gicastillo** [comment]
Estuve pensandolo mejor, y creo que cuesta tanto pensar el ejemplo porque estas dos preguntas tienen objetivos similares:

> ¿Qué quieres que haga tu autoridad para solucionar el problema? (3 líneas)

> ¿Qué avances concretos esperas que se logren durante el periodo del alcalde (4 años)?

Propongo que dejemos las 2, para que las personas respondan cosas más generales (no necesariamente medibles) en la primera pregunta que es más abierta, y que la segunda sea para que acoten y piensen en algo más medible, concreto. Un ejemplo para explicarlo mejor que vi en el mail sobre Valdivia.

 > ¿Qué quieres que haga tu autoridad para solucionar el problema? (3 líneas)
Crear una ciclovia que circunvale Valdivia

> ¿Qué avances concretos esperas que se logren durante el periodo del alcalde (4 años)?
Aumentar en un 20% la cantidad de ciclovías en la ciudad

Así, en la primera se responde la solución pensada a largo plazo, y en la segunda algo realizable en el periodo, y que encamina hacia la solución a largo plazo.

Qué opinan de esto?

**Comment by lfalvarez** [comment]
Implica un cambio de orden?
Están bien esos ejmplos?

**Comment by gicastillo** [comment]
-Dejaría ese mismo orden, porque la respuesta "ideal" sale primero, es más fácil pensar en esa.
-Esos ejemplos me hicieron mucho sentido, no sé al resto pero a mi me parecen bien (aunque igual pensaré ejemplos de otras áreas)

**Comment by lfalvarez** [comment]
Están super simples :+1:  se imprime

**Comment by margamaira** [comment]
Creo que lo que dice Gabriel es exactamente lo que buscamos: una aspiración más grande y un objetivo medible y concreto. Encuentro que están super buenos los ejemplos. ¿Necesitamos más?

**Comment by lfalvarez** [comment]
uy me gustaría caleta ver los otros que nos van quedando :smile:
