### ISSUE TITLE
Detalle: falta indicar cantidad de líneas

### ISSUE THREAD

**Issue by gicastillo** [ciudadanointeligente/votainteligente-portal-electoral#333]
[https://github.com/ciudadanointeligente/votainteligente-portal-electoral/blob/master/popular_proposal/forms.py#L57](url)

Creo que no funciona el link, pero está en el archivo: forms.py, línea 57

@lfalvarez

**Comment by lfalvarez** [comment]
Perfecto! :sparkles: y estamos hablando de 2 no es cierto?

**Comment by gicastillo** [comment]
2 o 3 debería estar bien. Acabo de tratar de llegar al límite y nunca me avisa tope, debería ser así?

**Comment by lfalvarez** [comment]
no lo sé y cual es el tope?

**Comment by lfalvarez** [comment]
creo que no tiene tope, quizás debamos colocarselo.

**Comment by gicastillo** [comment]
No tiene tope! Yo le pondría 3 líneas.

**Comment by lfalvarez** [comment]
voy a probar con 512 caractéres
