### ISSUE TITLE
add picture of a candidate

### ISSUE THREAD

**Issue by jdgarrido** [ciudadanointeligente/votainteligente-portal-electoral#344]
cuando edito un candidato por el administrador y le agrego una imagen, por ejemplo
https://panosz.files.wordpress.com/2012/03/mystery.jpg la almacena, pero al mostrar en el perfil, obtengo el siguiente error

![screenshot from 2016-04-20 15-19-08](https://cloud.githubusercontent.com/assets/586722/14685582/5fe90ff8-070b-11e6-9265-1704efe4f02a.png)

según yo, tengo la db con sus migraciones al día.

**Comment by lfalvarez** [comment]
Hola @jdgarrido:
Podrías probar con 
```
>> pip install -r requirements.txt
>> ./manage.py migrate
```

En https://github.com/ciudadanointeligente/votainteligente-portal-electoral/commit/46f08040a707c3738fb8e058d58fd0e6b13d8880 cambiamos la versión requerida de [sorl-thumbnail](https://github.com/mariocesar/sorl-thumbnail/) por la 12.4a1 la que tiene migraciones y antes no las tenía.

**Comment by jdgarrido** [comment]
@lfalvarez todo bien!
