### ISSUE TITLE
No se están desplegando los contenidos en el preview de la propuesta

### ISSUE THREAD

**Issue by camargozzini** [ciudadanointeligente/votainteligente-portal-electoral#459]
Actualmente esta así:

![screen shot 2016-08-10 at 15 59 14](https://cloud.githubusercontent.com/assets/1230740/17568787/3cd486d6-5f13-11e6-98b4-f417799c07dc.png)

Y debería estar así:
![screen shot 2016-08-10 at 16 00 05](https://cloud.githubusercontent.com/assets/1230740/17568806/577479a6-5f13-11e6-8242-58702d8e6e5c.png)

**Comment by camargozzini** [comment]
wenaaaaaaaa

**Comment by lfalvarez** [comment]
Se arregló no es cierto?
