### ISSUE TITLE
Backend candidato: al entrar que salga desplegado el contenido de completa tu perfil en vez de en blanco

### ISSUE THREAD

**Issue by camargozzini** [ciudadanointeligente/votainteligente-portal-electoral#570]
Ahora esta así:
![screen shot 2016-09-09 at 15 22 48](https://cloud.githubusercontent.com/assets/1230740/18398039/393aa906-76a1-11e6-9a9a-b64e47db3d04.png)
Me gustaría que se viera así:
![screen shot 2016-09-09 at 15 24 08](https://cloud.githubusercontent.com/assets/1230740/18398045/44987198-76a1-11e6-8167-fb19d3d12040.png)

**Comment by lfalvarez** [comment]
Ya!
