### ISSUE TITLE
Fondo background hace difícil la lectura.

### ISSUE THREAD

**Issue by twolfvb** [ciudadanointeligente/votainteligente-portal-electoral#646]
Se está usando el color de fondo #FFC80A, un amarillo chillón.
Se vería mucho mejor algún color ligeramente mas oscuro, para que no moleste para leer, como por ejemplo #77AA0A.

**Comment by lfalvarez** [comment]
weeenaaa ejalé, estoy conversando con mi compañera @camargozzini (AKA: la mejor) y cachai que me dice que el cambio es muy radical, pero sin embargo, tenemos una contra propuesta:
![group](https://cloud.githubusercontent.com/assets/585757/19525924/fa2cacf6-95f8-11e6-80df-ef870338bd7f.png)

Qué pensai?
