### ISSUE TITLE
Apadrinamientos. Implicancias de apadrinamientos

### ISSUE THREAD

**Issue by lfalvarez** [ciudadanointeligente/votainteligente-portal-electoral#705]
* [x] Se envía un mail a la org apadrinadora con los datos del propositor (mail, lo que tengamos). (se la enviamos a las dos para que se pongan en contacto?????)
* [x] Desplegar en la propuesta quienes son las organizaciones que patrocinan.
* [x] En el perfil de la organización aparecen las propuestas apadrinadas.

**Comment by octagrammer** [comment]
creo que para promover los apadrinamientos deberíamos hacer con las orgs lo mismo que queremos hacer con los candidatos: enviarles todas las propuestas generadas en los temas en que trabajan y que tendrán la posibilidad de adherir a ellas en la plataforma.
La wea es en qué momento las orgs definen sus temas de trabajo, que tienen que ser las mismas que los tags de las propuestas para poder hacer el cruce. Quizás un momento es cuando se hacen el perfil.
Quizás se podría agregar una sección en el backend del perfil de las orgs donde se vayan reflejando todas las propuestas de esas áreas, así como tenemos pensado hacerlo para los candidatos, pero con filtros temáticos definidos a partir del perfil de la org.
En esa misma sección arriba se definen los términos y condiciones del apadrinamiento que tengo que pensarlas aún

**Comment by lfalvarez** [comment]
* Actualmente existe la sección que se llama ["Mis apoyos"](https://github.com/ciudadanointeligente/votainteligente-portal-electoral/blob/master/votai_general_theme/templates/backend_citizen/my_supports.html#L24) está diseñado para ciudadanos y ofrece la lista de propuestas que un ciudadano ha apoyado.
* Podríamos hacer la misma cosa pero con una opción donde las organizaciones se pueden subscribir a temas.

**Comment by octagrammer** [comment]
Claro, creo que tiene que existir una sección de "mis apoyos", pero otra donde pueda explorar todas las propuestas de ciertas áreas para ver cuáles de esa va a apoyar y que pasaran a la sección "mis apoyos". Así como con los candidatos, sería ideal que sea todo desde el backend y en la misma plataforma para que sea ágil

**Comment by damian-garrido** [comment]
"_La wea es en qué momento las orgs definen sus temas de trabajo, que tienen que ser las mismas que los tags de las propuestas para poder hacer el cruce. Quizás un momento es cuando se hacen el perfil._"
creo q el mejor momento es cuando se crean el perfil, acá yo pensaba que se les debiese pedir un máximo de áreas de interes.
Entonces después viene la otra parte, donde los creadores de propuestas califican en algunas aŕeas su propuesta, acá sin límites.
Así, cuando una ONG va a revisar la sección "A quién podría apoyar", aparezcan acá filtradas por los temas de la organización. Si una ONG no tiene sus temas definidos, les exigimos que los agregue para entregarles un mejor servicio.
que piensan? @lfalvarez @octagrammer @mcorvera @nicofernandezrod

**Comment by octagrammer** [comment]
Totalmente de acuerdo!

**Comment by lfalvarez** [comment]
Y las suscripciones hace sentido??? #707 es muy similar pero no les exigimos cosas.

**Comment by lfalvarez** [comment]
@damian-garrido @jdgarrido Ayura:

Cuando una organización le presta ropa a una propuesta, lo hice, pero me quedó horriule, como el trauco, mire:

![image](https://user-images.githubusercontent.com/585757/26954160-7512d7a8-4c7c-11e7-8522-d5dc59dd4124.png)

Ayuremeeee por favoooor jefeeee!!! Mire, acá es donde comienza el weveo -> https://github.com/ciudadanointeligente/votainteligente-portal-electoral/pull/715/files#diff-4857b23ebc05f438f4d88e7e4221b622R323
