### ISSUE TITLE
Lugar donde subir antecedentes/documentos y donde poner "encuentros"

### ISSUE THREAD

**Issue by nicofernandezrod** [ciudadanointeligente/votainteligente-portal-electoral#713]
Me parece que en el paso 5, donde está el resumen de tu propuesta "terminada", debería también estar el espacio para subir foto, antecedentes o documentos. Esto porque da por entender que al "enviar la propuesta" y aceptar los términos y condiciones, ya está lista tu propuesta. Me imagino que para muchas organizaciones o grupos van a querer tener un desarrollo más grande y específico, cosa que no quedarán contentos solo con poner el resumen que sale en el grupo 5. 

Lo mismo para donde poner que esta propuesta fue elaborada desde un "encuentro ciudadano". Me parece que esta debiese ir en el último paso (5) para que tipo salga esta propuesta con el sello de haber sido creada en un encuentro ciudadano. 

esooooooo corazones para todes

**Comment by lfalvarez** [comment]
OOOOEEEEEEE!!!!
cachai que en #714 hicimos que la gente tuviera que confirmar que subieron su propuesta! y entonces te redirige automáticamente al perfil de tu propuesta, pero podríamos redirigir a "Actualiza tus datos".
