### ISSUE TITLE
Confirmar mail de la persona que propone al final de la propuesta.

### ISSUE THREAD

**Issue by nicofernandezrod** [ciudadanointeligente/votainteligente-portal-electoral#714]
Para poder tener un buen seguimiento de las propuestas recomienda Laura que pidamos por propuesta un correo. Esto con el fin de poder tener contacto directo con la persona o agrupación que haga una propuesta. No todos los correos que se ocupan para crear usuarios son los que las personas utilizan normalmente (ej: si entra con facebook) por lo que sería bueno sugerir que nos den su correo oficial.

**Comment by lfalvarez** [comment]
Ahora al finalizar el wizard se ve el siguiente mensaje:
![image](https://user-images.githubusercontent.com/585757/27108580-0e55b87a-506c-11e7-8353-7f58685571f4.png)
y se envía el siguiente mail a la persona que creó la propuesta:
![image](https://user-images.githubusercontent.com/585757/27108613-3a8b53b4-506c-11e7-85b4-2a8ff5758029.png)
Y cuando uno hace click en el link del mail, entonces te lleva hacia la siguiente web:
![image](https://user-images.githubusercontent.com/585757/27109655-35e8e6cc-5072-11e7-8c23-964c55669882.png)
