### ISSUE TITLE
Se envía un mail a la org apadrinadora con los datos del propositor (mail, lo que tengamos). (se la enviamos a las dos para que se pongan en contacto?????)

### ISSUE THREAD

**Issue by lfalvarez** [ciudadanointeligente/votainteligente-portal-electoral#718]

**Comment by damian-garrido** [comment]
@octagrammer @mcorvera 
tenemos dudas respecto de lo que ocurre cuando hay un match entre una orga y un ciudadano.
a mi me da la impresion de que puede ocurrir que en ambos lados o de parte de un lado, no pesque su correo y sea una conversaci'on al aire.
qu'e opinan?
