### ISSUE TITLE
Mejorar el mail que se le envía a la organización que recién ha apadrinado y al propositor

### ISSUE THREAD

**Issue by lfalvarez** [ciudadanointeligente/votainteligente-portal-electoral#720]
Actualmente sólo les decimos que los queremos mucho pero faltan cosas.

Estos son los mails que se envían:
Este es el asunto del mail:
https://github.com/ciudadanointeligente/votainteligente-portal-electoral/blob/master/votai_general_theme/templates/mails/new_sponsorshipnotification_subject.html
Y este es el cuerpo del mail:
https://github.com/ciudadanointeligente/votainteligente-portal-electoral/blob/master/votai_general_theme/templates/mails/new_sponsorshipnotification_body.html

**Comment by lfalvarez** [comment]
@octagrammer @mcorvera
tenemos dudas respecto de lo que ocurre cuando hay un match entre una orga y un ciudadano.
a mi me da la impresion de que puede ocurrir que en ambos lados o de parte de un lado, no pesque su correo y sea una conversaci'on al aire.
qu'e opinan?


vía @damian-garrido

**Comment by octagrammer** [comment]
con match se refieren a que una org le da like a una propuesta ciudadana o al reve o ambos??

Pienso que tenemos que resolver ciertas cuestiones, en el sentido de si van a haber intensidades de apadrinamiento.

Por ejemplo, creo que deberíamos permitir a las orgs personalizar el correo de apadrinamiento poniendo cierta información que quieran darle al que apadrinan. Como contacto, eventos, personas de la org en su zona geográfica, noticias , etc.

Eso tiene el problema de que probablemente pocos lo van a hacer y que puede inhibir darle likes a propuestas pq las orgs se pueden sentir muy comprometidos.

Entonces, se me ocurre:
1. Dar like debe implicar en principio sólo que en la plataforma se visibiliza eso tanto en el perfil de la org y en la propuesta.
2. Se envía un mail de contacto en el que se notifica el apadrinamiento y en el que se sugieren ciertas acciones de conexión. CUÁLES?? no sé. Quizás debamos preguntarle a las orgs qué creen que podría ir ahí.

Pregunta, cuándo un usuario le da like a una propuesta de org también se notifica a la org???

**Comment by lfalvarez** [comment]
> Pregunta, cuándo un usuario le da like a una propuesta de org también se notifica a la org???
Nones

**Comment by lfalvarez** [comment]
> Entonces, se me ocurre:
Dar like debe implicar en principio sólo que en la plataforma se visibiliza eso tanto en el perfil de la org y en la propuesta.
Se envía un mail de contacto en el que se notifica el apadrinamiento y en el que se sugieren ciertas acciones de conexión. CUÁLES?? no sé. Quizás debamos preguntarle a las orgs qué creen que podría ir ahí.

Chan!!! Aquí está lo que se me había ocurrido, pensaba en "Intercambien mails/ teléfonos" y una especie de _call to action_. Algo así como:
* intercambien agenda de actividades, para ver dónde pueden generarse sinergias
* tengan una reunión, si pueden en físico y si no por skype, les recomendamos utilizar appear.in.

No se me ocurren más cosas pero podríamos dejarlo más abierto.

**Comment by nicofernandezrod** [comment]
Me parece el último comentario de Octa.

1.- podríamos pedirle a las organizaciones cómo les gustaría interactuar (o hasta qué límite) con un usuario al cual le ponen <3 a su propuesta

2.- podríamos hacer una lista tipo:
a) mandar mail (click aquí)
b) enviar teléfono de contacto (click aquí)
c) pedir reunión (click aquí)

y que cada organización pueda decidir qué nivel de interacción quiere con cada propuesta laikeada.

**Comment by lfalvarez** [comment]
Después de una reunión rapidita quedamos en lo siguiente:
* A la organización que apoyo le ofrecemos que además le incluya un mensajito. En este mensajito le hacemos algunas recomendaciones como por ejemplo, "Me puedes contactar en este teléfono" o  "Me gustaría ofrecerte una reunión".
* Se envían dos mails uno a la organización que apoya y donde le recordamos que sobre su apoyo (sólo para el registro). Si tenemos datos de contacto públicos de la persona que hizo la propuesta se los incluimos.
```

Estimada Fundación Ciudadano Inteligente:
Te recordamos que acabas de apoyar la propuesta "Huesos de calidad" y que les enviaste el siguiente mensaje:

Fiera, cuida al jefe por que derepente tiene prohibido manejar.
Nos puedes contactar en perritochiquitito@votainteligente.cl y en el teléfono 5555rriente.
Cuando te puedes juntar con nosotros?

Te queríamos contar que Fiera dejó los siguientes datos públicos de contacto:

Acá en la casa del jefe @damian-garrido.

Ahora no te queda más que esperar que Fiera se contacte contigo, mientras tanto puedes ver tu apoyo a esta propuesta reflejado en tu perfil (votainteligente.cl/organizaciones/ciudadanoi) y en la propuesta (votainteligente.cl/propuestas/huesos-de-calidad).

Te queremos mucho.
--
El equipo de VotaInteligente.cl 
```
* El segundo es para quién realizó la propuesta con la información de contacto de la organización que apoyó, el mail es algo así.
```
Estimada Fiera:
Te queremos contar que la Fundación Ciudadano Inteligente acaba de apoyar de manera pública tu propuesta *Huesos de calidad*, te contamos que si respondes a este mail le llegará al encargado de la organización. Además te queremos contar que Fundación Ciudadano Inteligente te envió el siguiente mensaje al momento de apoyar tu propuesta:

Fiera, cuida al jefe por que derepente tiene prohibido manejar.
Nos puedes contactar en perritochiquitito@votainteligente.cl y en el teléfono 5555rriente.
Cuando te puedes juntar con nosotros?

Te recomendamos que respondas pronto a este mail para que concretes una buena cooperación.
Además puedes ver este apoyo en el perfil de la Fundación Ciudadano Inteligente(votainteligente.cl/organizaciones/ciudadanoi) y en tu propuesta (votainteligente.cl/propuestas/huesos-de-calidad) .
Te queremos mucho.
--
El equipo de VotaInteligente.cl

```
