### ISSUE TITLE
BREADCRUMBS : al revisar una propuesta, no puedes volver a ningun lado

### ISSUE THREAD

**Issue by damian-garrido** [ciudadanointeligente/votainteligente-portal-electoral#751]
no hay menú, ni migas de navegación ni nada.

https://votainteligente.cl/propuestas/detail/osc-articuladas-y-coordinadas-para-la-emergencia

revisando en local, cuando uno está logueado se ve el menú que permite crear o conocer propuestas además de poder acceder a la página principal

igual hay q hecharle un ojo

**Comment by lfalvarez** [comment]
Esto ya está @damian-garrido 

![image](https://user-images.githubusercontent.com/585757/29461514-0acf1d7e-83fa-11e7-8e1e-c2410b1c27cc.png)
